import type { Question } from "./questions";

export const EXTRA_QUESTIONS: Question[] = [
  // ── عام ──
  { id: "q321", category: "عام", difficulty: "easy", question: "ما هي أكبر دولة في العالم من حيث المساحة؟", options: ["روسيا", "كندا", "الصين", "أمريكا"], correctIndex: 0 },
  { id: "q322", category: "عام", difficulty: "easy", question: "ما هي عاصمة الأردن؟", options: ["عمّان", "بيروت", "بغداد", "صنعاء"], correctIndex: 0 },
  { id: "q323", category: "عام", difficulty: "easy", question: "ما هي أصغر دولة في العالم من حيث المساحة؟", options: ["مالطا", "الفاتيكان", "موناكو", "لوكسمبورغ"], correctIndex: 1 },
  { id: "q324", category: "عام", difficulty: "medium", question: "ما هو أطول سور دفاعي في العالم؟", options: ["سور هادريان", "سور الصين العظيم", "سور برلين", "سور الأطلسي"], correctIndex: 1 },
  { id: "q325", category: "عام", difficulty: "easy", question: "ما هي أكبر جزيرة في العالم؟", options: ["مدغشقر", "بورنيو", "غرينلاند", "سومطرة"], correctIndex: 2 },
  { id: "q326", category: "عام", difficulty: "easy", question: "ما هي العملة الرسمية في بريطانيا؟", options: ["اليورو", "الدولار", "الجنيه الإسترليني", "الفرنك"], correctIndex: 2 },
  { id: "q327", category: "عام", difficulty: "medium", question: "ما هي اللغة الأكثر تحدثاً في العالم كلغة أم؟", options: ["الإنجليزية", "الإسبانية", "الماندرين الصينية", "الفرنسية"], correctIndex: 2 },
  { id: "q328", category: "عام", difficulty: "medium", question: "ما هو أطول نهر في أوروبا؟", options: ["الراين", "الدانوب", "الفولغا", "التيبر"], correctIndex: 2 },
  { id: "q329", category: "عام", difficulty: "easy", question: "ما هي العملة الرسمية في دولة الإمارات؟", options: ["الريال", "الدرهم", "الدينار", "الجنيه"], correctIndex: 1 },
  { id: "q330", category: "عام", difficulty: "medium", question: "ما هي أكثر دولة في العالم من حيث عدد السكان؟", options: ["الصين", "الهند", "أمريكا", "إندونيسيا"], correctIndex: 1 },
  { id: "q331", category: "عام", difficulty: "medium", question: "ما هي أكبر بحيرة مياه عذبة في العالم من حيث المساحة؟", options: ["بحيرة بايكال", "بحيرة فيكتوريا", "بحيرة سوبيريور", "بحيرة تنجانيقا"], correctIndex: 2 },
  { id: "q332", category: "عام", difficulty: "easy", question: "ما هي عاصمة كندا؟", options: ["تورونتو", "مونتريال", "أوتاوا", "فانكوفر"], correctIndex: 2 },
  { id: "q333", category: "عام", difficulty: "easy", question: "ما هي العملة الرسمية في تركيا؟", options: ["الجنيه", "الليرة التركية", "الدينار", "الدرهم"], correctIndex: 1 },
  { id: "q334", category: "عام", difficulty: "hard", question: "كم عدد اللغات الرسمية في سويسرا؟", options: ["اثنتان", "ثلاث", "أربع", "خمس"], correctIndex: 2 },
  { id: "q335", category: "عام", difficulty: "medium", question: "ما هو أعلى شلال في العالم؟", options: ["شلال نياجرا", "شلال أنجل", "شلال فيكتوريا", "شلال إجوازو"], correctIndex: 1 },
  { id: "q336", category: "عام", difficulty: "easy", question: "في أي دولة يقع برج بيزا المائل؟", options: ["فرنسا", "إسبانيا", "إيطاليا", "اليونان"], correctIndex: 2 },
  { id: "q337", category: "عام", difficulty: "easy", question: "ما الدولة الملقبة بأرض الشمس المشرقة؟", options: ["الصين", "كوريا", "اليابان", "تايلاند"], correctIndex: 2 },
  { id: "q338", category: "عام", difficulty: "medium", question: "ما هو أكبر تجمع حضري في العالم من حيث السكان؟", options: ["نيودلهي", "شنغهاي", "طوكيو", "مكسيكو سيتي"], correctIndex: 2 },
  { id: "q339", category: "عام", difficulty: "easy", question: "ما هي عاصمة النمسا؟", options: ["زيورخ", "براغ", "فيينا", "ميونخ"], correctIndex: 2 },
  { id: "q340", category: "عام", difficulty: "hard", question: "كم عدد الدول الأعضاء في الاتحاد الأوروبي حالياً؟", options: ["25", "26", "27", "28"], correctIndex: 2 },
  // ── علوم ──
  { id: "q341", category: "علوم", difficulty: "easy", question: "ما هي أصلب مادة طبيعية معروفة؟", options: ["الحديد", "الألماس", "الكوارتز", "التنجستن"], correctIndex: 1 },
  { id: "q342", category: "علوم", difficulty: "medium", question: "ما هو العنصر الأكثر وفرة في القشرة الأرضية؟", options: ["السيليكون", "الألمنيوم", "الأكسجين", "الحديد"], correctIndex: 2 },
  { id: "q343", category: "علوم", difficulty: "medium", question: "ما الغاز الرئيسي الناتج عن النشاط البشري والمسبب للاحتباس الحراري؟", options: ["الأكسجين", "النيتروجين", "ثاني أكسيد الكربون", "الهيدروجين"], correctIndex: 2 },
  { id: "q344", category: "علوم", difficulty: "easy", question: "ما هي وحدة قياس شدة التيار الكهربائي؟", options: ["الفولت", "الواط", "الأمبير", "الأوم"], correctIndex: 2 },
  { id: "q345", category: "علوم", difficulty: "easy", question: "ماذا نسمي تحول الماء من سائل إلى بخار؟", options: ["التجمد", "التكاثف", "التبخر", "الترسيب"], correctIndex: 2 },
  { id: "q346", category: "علوم", difficulty: "easy", question: "ما الكائن الذي ينتج لنا الحرير الطبيعي؟", options: ["النحلة", "العنكبوت", "دودة القز", "الخنفساء"], correctIndex: 2 },
  { id: "q347", category: "علوم", difficulty: "medium", question: "كم عدد فقرات رقبة الزرافة؟", options: ["سبع", "خمس عشرة", "أربعون", "اثنتان وخمسون"], correctIndex: 0 },
  { id: "q348", category: "علوم", difficulty: "hard", question: "ما هي أطول خلية في جسم الإنسان؟", options: ["خلية العضلة", "الخلية العصبية", "خلية العظم", "خلية الدم"], correctIndex: 1 },
  { id: "q349", category: "علوم", difficulty: "medium", question: "ما الغاز الخامل المستخدم تقليدياً في ملء المصابيح المتوهجة؟", options: ["الهيدروجين", "الهيليوم", "الأرغون", "النيون"], correctIndex: 2 },
  { id: "q350", category: "علوم", difficulty: "easy", question: "ماذا يقيس جهاز البارومتر؟", options: ["سرعة الرياح", "الضغط الجوي", "نسبة الرطوبة", "درجة الحرارة"], correctIndex: 1 },
  { id: "q351", category: "علوم", difficulty: "medium", question: "ما هو العدد الذري لعنصر الكربون؟", options: ["4", "6", "8", "12"], correctIndex: 1 },
  { id: "q352", category: "علوم", difficulty: "easy", question: "ما أصغر وحدة في العنصر الكيميائي تحتفظ بخصائصه؟", options: ["الذرة", "الإلكترون", "النواة", "الأيون"], correctIndex: 0 },
  { id: "q353", category: "علوم", difficulty: "medium", question: "ماذا نسمي عملية خروج بخار الماء من أوراق النباتات؟", options: ["التنفس", "النتح", "الامتصاص", "التخمر"], correctIndex: 1 },
  { id: "q354", category: "علوم", difficulty: "medium", question: "أي من الحيوانات التالية ليس من الثدييات؟", options: ["الحوت", "الخفاش", "التمساح", "الدلفين"], correctIndex: 2 },
  { id: "q355", category: "علوم", difficulty: "easy", question: "ما العضو الذي يفرز هرمون الأنسولين؟", options: ["الكبد", "المعدة", "البنكرياس", "الطحال"], correctIndex: 2 },
  { id: "q356", category: "علوم", difficulty: "easy", question: "مقياس ريختر يقيس قوة ماذا؟", options: ["الأعاصير", "الزلازل", "البراكين", "الفيضانات"], correctIndex: 1 },
  { id: "q357", category: "علوم", difficulty: "easy", question: "ما المادة الشائعة التي توجد طبيعياً في حالاتها الثلاث؟", options: ["الزيت", "الماء", "الكحول", "الزئبق"], correctIndex: 1 },
  { id: "q358", category: "علوم", difficulty: "medium", question: "ذوبان الجليد وتحوله إلى ماء تغير من نوع: ماذا؟", options: ["كيميائي", "فيزيائي", "نووي", "بيولوجي"], correctIndex: 1 },
  { id: "q359", category: "علوم", difficulty: "medium", question: "ما وظيفة الخلايا المخروطية في شبكية العين؟", options: ["الرؤية الليلية", "الرؤية الملونة", "ضبط التوازن", "إفراز الدموع"], correctIndex: 1 },
  { id: "q360", category: "علوم", difficulty: "easy", question: "ما هي وحدة قياس الطاقة في النظام الدولي؟", options: ["الجول", "الباسكال", "الأمبير", "الهرتز"], correctIndex: 0 },
  { id: "q361", category: "علوم", difficulty: "medium", question: "ما العضو الذي يخزن العصارة الصفراوية؟", options: ["البنكرياس", "الطحال", "المرارة", "الكلية"], correctIndex: 2 },
  { id: "q362", category: "علوم", difficulty: "hard", question: "ما الظاهرة الطبيعية التي تسبب المد والجزر في المقام الأول؟", options: ["جاذبية القمر", "دوران الأرض", "الرياح", "حرارة الشمس"], correctIndex: 0 },
  // ── جغرافيا ──
  { id: "q363", category: "جغرافيا", difficulty: "medium", question: "مضيق جبل طارق يفصل بين: ماذا؟", options: ["تونس وإيطاليا", "المغرب وإسبانيا", "مصر والسعودية", "تركيا واليونان"], correctIndex: 1 },
  { id: "q364", category: "جغرافيا", difficulty: "hard", question: "ما هي عاصمة سويسرا؟", options: ["جنيف", "زيورخ", "برن", "بازل"], correctIndex: 2 },
  { id: "q365", category: "جغرافيا", difficulty: "hard", question: "ما هو أكبر خليج في العالم من حيث المساحة؟", options: ["الخليج العربي", "خليج المكسيك", "خليج البنغال", "خليج ألاسكا"], correctIndex: 2 },
  { id: "q366", category: "جغرافيا", difficulty: "medium", question: "ما الجبال التي تفصل قارة أوروبا عن آسيا؟", options: ["جبال الألب", "جبال القوقاز", "جبال الأورال", "جبال الكاربات"], correctIndex: 2 },
  { id: "q367", category: "جغرافيا", difficulty: "medium", question: "أي دولة من التالية دولة غير ساحلية؟", options: ["البرتغال", "اليونان", "سويسرا", "النرويج"], correctIndex: 2 },
  { id: "q368", category: "جغرافيا", difficulty: "easy", question: "كم عدد الدول العربية؟", options: ["18", "20", "22", "25"], correctIndex: 2 },
  { id: "q369", category: "جغرافيا", difficulty: "medium", question: "ما هي عاصمة البرازيل؟", options: ["ريو دي جانيرو", "ساو باولو", "برازيليا", "سلفادور"], correctIndex: 2 },
  { id: "q370", category: "جغرافيا", difficulty: "easy", question: "في أي قارة تقع جبال الأنديز؟", options: ["أمريكا الشمالية", "أمريكا الجنوبية", "آسيا", "أوروبا"], correctIndex: 1 },
  { id: "q371", category: "جغرافيا", difficulty: "easy", question: "في أي منطقة تقع صحراء الربع الخالي؟", options: ["شمال أفريقيا", "شبه الجزيرة العربية", "آسيا الوسطى", "أستراليا"], correctIndex: 1 },
  { id: "q372", category: "جغرافيا", difficulty: "medium", question: "في أي مدينة يقع مضيق البوسفور؟", options: ["القاهرة", "إسطنبول", "أثينا", "موسكو"], correctIndex: 1 },
  { id: "q373", category: "جغرافيا", difficulty: "medium", question: "ما هي أصغر الدول العربية من حيث المساحة؟", options: ["قطر", "جيبوتي", "البحرين", "الكويت"], correctIndex: 2 },
  { id: "q374", category: "جغرافيا", difficulty: "easy", question: "في أي قارة يقع نهر الأمازون؟", options: ["أفريقيا", "آسيا", "أمريكا الجنوبية", "أوقيانوسيا"], correctIndex: 2 },
  { id: "q375", category: "جغرافيا", difficulty: "easy", question: "ما هي أكبر دولة من حيث المساحة في أمريكا الجنوبية؟", options: ["الأرجنتين", "البرازيل", "بيرو", "كولومبيا"], correctIndex: 1 },
  { id: "q376", category: "جغرافيا", difficulty: "medium", question: "مضيق هرمز يربط الخليج العربي بأي مسطح مائي؟", options: ["البحر الأحمر", "بحر عمان", "البحر المتوسط", "البحر الأسود"], correctIndex: 1 },
  { id: "q377", category: "جغرافيا", difficulty: "hard", question: "ما هي عاصمة نيوزيلندا؟", options: ["أوكلاند", "كرايستشيرش", "ويلينغتون", "هاميلتون"], correctIndex: 2 },
  { id: "q378", category: "جغرافيا", difficulty: "medium", question: "في أي دولة يقع جبل كليمنجارو؟", options: ["كينيا", "أوغندا", "تنزانيا", "إثيوبيا"], correctIndex: 2 },
  { id: "q379", category: "جغرافيا", difficulty: "easy", question: "قناة السويس تربط أي بحرين؟", options: ["الأحمر والهندي", "المتوسط والبحر الأحمر", "الأحمر والخليج", "المتوسط والأسود"], correctIndex: 1 },
  { id: "q380", category: "جغرافيا", difficulty: "medium", question: "في أي مدينة هندية يقع تاج محل؟", options: ["نيودلهي", "أغرا", "مومباي", "جايبور"], correctIndex: 1 },
  // ── رياضيات ──
  { id: "q381", category: "رياضيات", difficulty: "easy", question: "كم يساوي 11 × 11؟", options: ["101", "111", "121", "131"], correctIndex: 2 },
  { id: "q382", category: "رياضيات", difficulty: "medium", question: "ما هو العدد الأولي الزوجي الوحيد؟", options: ["1", "2", "4", "6"], correctIndex: 1 },
  { id: "q383", category: "رياضيات", difficulty: "medium", question: "كم تساوي نسبة 15% من 200؟", options: ["20", "25", "30", "35"], correctIndex: 2 },
  { id: "q384", category: "رياضيات", difficulty: "medium", question: "كم يساوي 8 أس 3؟", options: ["64", "256", "512", "1024"], correctIndex: 2 },
  { id: "q385", category: "رياضيات", difficulty: "medium", question: "كم يساوي مربع (5 + 3)؟", options: ["16", "32", "64", "81"], correctIndex: 2 },
  { id: "q386", category: "رياضيات", difficulty: "easy", question: "ما محيط مربع طول ضلعه 6؟", options: ["12", "24", "36", "48"], correctIndex: 1 },
  { id: "q387", category: "رياضيات", difficulty: "medium", question: "ما مساحة مثلث قاعدته 10 وارتفاعه 6؟", options: ["16", "30", "60", "15"], correctIndex: 1 },
  { id: "q388", category: "رياضيات", difficulty: "easy", question: "كم يساوي 0.5 × 40؟", options: ["2", "20", "200", "80"], correctIndex: 1 },
  { id: "q389", category: "رياضيات", difficulty: "medium", question: "أي عدد من التالية عدد مركب فردي؟", options: ["7", "9", "11", "13"], correctIndex: 1 },
  { id: "q390", category: "رياضيات", difficulty: "hard", question: "إذا كانت الساعة تشير إلى 3:15، فكم الزاوية بين عقربي الساعات والدقائق؟", options: ["0 درجة", "7.5 درجة", "15 درجة", "30 درجة"], correctIndex: 1 },
  { id: "q391", category: "رياضيات", difficulty: "medium", question: "ما هي الزاوية المتممة لزاوية قياسها 40 درجة؟", options: ["40 درجة", "50 درجة", "140 درجة", "320 درجة"], correctIndex: 1 },
  { id: "q392", category: "رياضيات", difficulty: "easy", question: "كم يساوي 2 أس 10؟", options: ["100", "512", "1000", "1024"], correctIndex: 3 },
  { id: "q393", category: "رياضيات", difficulty: "medium", question: "كم يساوي نصف نسبة 25% من 800؟", options: ["50", "100", "200", "400"], correctIndex: 1 },
  { id: "q394", category: "رياضيات", difficulty: "easy", question: "ما هو المتوسط الحسابي للأعداد 4 و6 و8؟", options: ["5", "6", "7", "8"], correctIndex: 1 },
  { id: "q395", category: "رياضيات", difficulty: "medium", question: "كم يساوي 100 ÷ 0.2؟", options: ["20", "50", "200", "500"], correctIndex: 3 },
  { id: "q396", category: "رياضيات", difficulty: "easy", question: "كم عدد أضلاع الشكل العشاري؟", options: ["8", "9", "10", "12"], correctIndex: 2 },
  { id: "q397", category: "رياضيات", difficulty: "medium", question: "كم يساوي 14 × 15؟", options: ["180", "200", "210", "240"], correctIndex: 2 },
  { id: "q398", category: "رياضيات", difficulty: "hard", question: "إذا تضاعف نصف قطر دائرة، فكم تصبح مساحتها؟", options: ["مرتين", "4 أضعاف", "8 أضعاف", "تبقى ثابتة"], correctIndex: 1 },
  { id: "q399", category: "رياضيات", difficulty: "easy", question: "كم تساوي نسبة 25% من 60؟", options: ["10", "15", "20", "25"], correctIndex: 1 },
  { id: "q400", category: "رياضيات", difficulty: "hard", question: "كم يساوي 7 عاملي (7!)؟", options: ["720", "5040", "50400", "40320"], correctIndex: 1 },
  { id: "q401", category: "رياضيات", difficulty: "hard", question: "كم يساوي 36 ÷ 0.75؟", options: ["27", "48", "44", "52"], correctIndex: 1 },
  { id: "q402", category: "رياضيات", difficulty: "hard", question: "كم عدد الأصفار في ناتج 10 عاملي (10!)؟", options: ["1", "2", "3", "4"], correctIndex: 1 },
  // ── لغة ──
  { id: "q403", category: "لغة", difficulty: "medium", question: "ما هو جمع كلمة مصيبة؟", options: ["مصايب", "مصائب", "مصائيب", "مصيبات"], correctIndex: 1 },
  { id: "q404", category: "لغة", difficulty: "medium", question: "ما هو مفرد كلمة أشياء؟", options: ["شائ", "شيء", "شيئ", "شياء"], correctIndex: 1 },
  { id: "q405", category: "لغة", difficulty: "medium", question: "ما هو مرادف كلمة بصيرة؟", options: ["حيرة", "غفلة", "فطنة", "ضلال"], correctIndex: 2 },
  { id: "q406", category: "لغة", difficulty: "easy", question: "ما هو ضد كلمة كرم؟", options: ["شجاعة", "لطف", "بخل", "جود"], correctIndex: 2 },
  { id: "q407", category: "لغة", difficulty: "easy", question: "ما هو فعل الأمر من الفعل كتب؟", options: ["كاتب", "مكتوب", "اكتب", "كتابة"], correctIndex: 2 },
  { id: "q408", category: "لغة", difficulty: "medium", question: "أي كلمة من التالية تبدأ بهمزة وصل؟", options: ["استخرج", "أمل", "إصلاح", "إنعام"], correctIndex: 0 },
  { id: "q409", category: "لغة", difficulty: "hard", question: "ما هو جمع كلمة حرباء؟", options: ["حرباوات", "حرابي", "حربات", "حرباءات"], correctIndex: 1 },
  { id: "q410", category: "لغة", difficulty: "medium", question: "ما هو مثنى كلمة ساعي؟", options: ["ساعيين", "ساعيان", "ساعون", "ساعي"], correctIndex: 1 },
  // ── لغة (تكملة) ──
  { id: "q411", category: "لغة", difficulty: "medium", question: "ما حرف العلة في الفعل يقول؟", options: ["الألف", "الواو", "الياء", "لا يوجد"], correctIndex: 1 },
  { id: "q412", category: "لغة", difficulty: "easy", question: "ما هو ضد كلمة شجاعة؟", options: ["قوة", "جبن", "إقدام", "جرأة"], correctIndex: 1 },
  { id: "q413", category: "لغة", difficulty: "easy", question: "ما هو مرادف كلمة صامد؟", options: ["متراجع", "خائف", "ثابت", "نائم"], correctIndex: 2 },
  { id: "q414", category: "لغة", difficulty: "easy", question: "ما هو مفرد كلمة قضايا؟", options: ["قضاء", "قاضي", "قضية", "قضاة"], correctIndex: 2 },
  { id: "q415", category: "لغة", difficulty: "easy", question: "أي كلمة من التالية كلمة معرفة؟", options: ["كتاب", "قلم", "المكتب", "ورق"], correctIndex: 2 },
  { id: "q416", category: "لغة", difficulty: "hard", question: "ما هو الجذر الثلاثي للفعل انطلق؟", options: ["طلق", "نطلق", "أطلق", "لقط"], correctIndex: 0 },
  { id: "q417", category: "لغة", difficulty: "medium", question: "همزة كلمة أمل همزة: ماذا؟", options: ["وصل", "قطع", "مد", "لام"], correctIndex: 1 },
  { id: "q418", category: "لغة", difficulty: "medium", question: "ما هي الكلمة الصحيحة إملائياً؟", options: ["مسؤول", "مسؤل", "مسئول", "مسوئل"], correctIndex: 0 },
  // ── منطق ──
  { id: "q419", category: "منطق", difficulty: "easy", question: "ما العدد التالي في المتتالية: 3، 6، 12، 24، ...؟", options: ["36", "40", "48", "60"], correctIndex: 2 },
  { id: "q420", category: "منطق", difficulty: "hard", question: "كم شهراً في السنة يحتوي على 28 يوماً؟", options: ["فبراير فقط", "فبراير ويونيو", "كل الشهور", "شهر واحد فقط"], correctIndex: 2 },
  { id: "q421", category: "منطق", difficulty: "easy", question: "اشتريت 3 أقلام سعر كل منها 2 ودفعت 10، فكم المتبقي معك؟", options: ["6", "4", "2", "8"], correctIndex: 1 },
  { id: "q422", category: "منطق", difficulty: "medium", question: "عمر الأب ضعف عمر ابنه ومجموع عمريهما 60، فكم عمر الأب؟", options: ["20", "30", "40", "45"], correctIndex: 2 },
  { id: "q423", category: "منطق", difficulty: "medium", question: "في سباق: B خلف C مباشرة و A خلف B مباشرة، فمن في المقدمة؟", options: ["A", "B", "C", "غير محدد"], correctIndex: 2 },
  { id: "q424", category: "منطق", difficulty: "medium", question: "إذا كانت اليد الواحدة لها 5 أصابع، فكم أصبعاً في 10 أيدٍ؟", options: ["10", "20", "50", "100"], correctIndex: 2 },
  { id: "q425", category: "منطق", difficulty: "hard", question: "ما الشيء الذي كلما أخذت منه كبر؟", options: ["الحبل", "الحفرة", "الصندوق", "الماء"], correctIndex: 1 },
  { id: "q426", category: "منطق", difficulty: "hard", question: "كم مرة يلتقي عقربا الساعة فوق بعضهما خلال 12 ساعة؟", options: ["12", "11", "10", "13"], correctIndex: 1 },
  { id: "q427", category: "منطق", difficulty: "easy", question: "ما العدد التالي في المتتالية: 1، 4، 9، 16، ...؟", options: ["20", "24", "25", "36"], correctIndex: 2 },
  { id: "q428", category: "منطق", difficulty: "hard", question: "كم يساوي نصف اثنين زائد اثنين (بالترتيب الحسابي)؟", options: ["2", "3", "4", "5"], correctIndex: 1 },
  { id: "q429", category: "منطق", difficulty: "hard", question: "إذا اصطادت 5 قطط 5 فئران في 5 دقائق، فكم دقيقة تحتاج 100 قطة لاصطياد 100 فأر؟", options: ["5", "20", "100", "25"], correctIndex: 0 },
  { id: "q430", category: "منطق", difficulty: "easy", question: "ما العدد التالي في المتتالية: 2، 3، 5، 7، 11، ...؟", options: ["12", "13", "15", "17"], correctIndex: 1 },
  { id: "q431", category: "منطق", difficulty: "hard", question: "أم لديها 5 بنات ولكل بنت أخ واحد، فكم عدد الأبناء؟", options: ["5", "4", "1", "6"], correctIndex: 2 },
  { id: "q432", category: "منطق", difficulty: "medium", question: "ما العدد التالي في المتتالية: 100، 90، 81، 73، 66، ...؟", options: ["61", "60", "59", "58"], correctIndex: 1 },
  { id: "q433", category: "منطق", difficulty: "hard", question: "قارب راسٍ وعليه سلم يتدلى حتى الماء، إذا ارتفع المد 10 سم فكم ترتفع درجة السلم عن الماء؟", options: ["10 سم", "لا ترتفع شيئاً", "5 سم", "20 سم"], correctIndex: 1 },
  { id: "q434", category: "منطق", difficulty: "easy", question: "سيارة تسير بسرعة 60 كم/س، كم كيلومتراً تقطع في نصف ساعة؟", options: ["15", "30", "45", "60"], correctIndex: 1 },
  { id: "q435", category: "منطق", difficulty: "medium", question: "ما أصغر عدد يقبل القسمة على 2 و3 و5 معاً؟", options: ["10", "15", "30", "60"], correctIndex: 2 },
  { id: "q436", category: "منطق", difficulty: "easy", question: "إذا كانت الساعة 12:00 تماماً، فكم تكون بعد 90 دقيقة؟", options: ["1:00", "1:30", "2:00", "2:30"], correctIndex: 1 },
  // ── تاريخ ──
  { id: "q437", category: "تاريخ", difficulty: "medium", question: "في أي عام سقطت بغداد بيد المغول؟", options: ["1250", "1258", "1260", "1268"], correctIndex: 1 },
  { id: "q438", category: "تاريخ", difficulty: "medium", question: "من هو مؤسس الدولة الأموية؟", options: ["عبد الملك بن مروان", "معاوية بن أبي سفيان", "الوليد بن عبد الملك", "يزيد بن معاوية"], correctIndex: 1 },
  { id: "q439", category: "تاريخ", difficulty: "hard", question: "من هو آخر الخلفاء العباسيين في بغداد؟", options: ["المتوكل", "المستعصم بالله", "المعتصم", "الأمين"], correctIndex: 1 },
  { id: "q440", category: "تاريخ", difficulty: "medium", question: "في أي عام دخلت حملة نابليون إلى مصر؟", options: ["1789", "1798", "1801", "1805"], correctIndex: 1 },
  { id: "q441", category: "تاريخ", difficulty: "medium", question: "من هو القائد المسلم الذي فتح بلاد السند؟", options: ["قتيبة بن مسلم", "محمد بن القاسم", "موسى بن نصير", "عقبة بن نافع"], correctIndex: 1 },
  { id: "q442", category: "تاريخ", difficulty: "medium", question: "من قاد المسلمين في معركة عين جالوت؟", options: ["صلاح الدين", "سيف الدين قطز", "الظاهر بيبرس", "نور الدين زنكي"], correctIndex: 1 },
  { id: "q443", category: "تاريخ", difficulty: "medium", question: "في أي عام سقطت غرناطة آخر معاقل المسلمين في الأندلس؟", options: ["1462", "1492", "1512", "1520"], correctIndex: 1 },
  { id: "q444", category: "تاريخ", difficulty: "medium", question: "في أي دولة اخترع غوتنبرغ المطبعة الحديثة؟", options: ["فرنسا", "إيطاليا", "ألمانيا", "إنجلترا"], correctIndex: 2 },
  { id: "q445", category: "تاريخ", difficulty: "medium", question: "من هو الشاعر اليوناني مؤلف ملحمتي الإلياذة والأوديسة؟", options: ["سقراط", "أفلاطون", "هوميروس", "أرسطو"], correctIndex: 2 },
  { id: "q446", category: "تاريخ", difficulty: "easy", question: "من هو أول رئيس للولايات المتحدة الأمريكية؟", options: ["أبراهام لينكولن", "جورج واشنطن", "توماس جيفرسون", "فرانكلين روزفلت"], correctIndex: 1 },
  { id: "q447", category: "تاريخ", difficulty: "medium", question: "ما الدولة التي أطلقت أول قمر صناعي في التاريخ؟", options: ["أمريكا", "الاتحاد السوفيتي", "بريطانيا", "فرنسا"], correctIndex: 1 },
  { id: "q448", category: "تاريخ", difficulty: "medium", question: "في أي عام قامت الثورة الفرنسية؟", options: ["1776", "1789", "1799", "1815"], correctIndex: 1 },
  { id: "q449", category: "تاريخ", difficulty: "medium", question: "ما الحضارة التي عرفت صناعة الورق أولاً؟", options: ["الفرعونية", "الرومانية", "الصينية", "الفارسية"], correctIndex: 2 },
  { id: "q450", category: "تاريخ", difficulty: "easy", question: "من أي دولة انطلقت حركة النهضة الفنية عصر النهضة؟", options: ["فرنسا", "إيطاليا", "إسبانيا", "هولندا"], correctIndex: 1 },
  { id: "q451", category: "تاريخ", difficulty: "hard", question: "من هو الطبيب العربي الذي اكتشف الدورة الدموية الصغرى؟", options: ["ابن سينا", "الرازي", "ابن النفيس", "ابن رشد"], correctIndex: 2 },
  { id: "q452", category: "تاريخ", difficulty: "medium", question: "من قاد جيش المسلمين في معركة القادسية؟", options: ["خالد بن الوليد", "سعد بن أبي وقاص", "أبو عبيدة بن الجراح", "المثنى بن حارثة"], correctIndex: 1 },
  { id: "q453", category: "تاريخ", difficulty: "easy", question: "في أي عام هاجر النبي محمد ﷺ إلى المدينة المنورة؟", options: ["610", "618", "622", "632"], correctIndex: 2 },
  { id: "q454", category: "تاريخ", difficulty: "medium", question: "ما أقدم جامعة في العالم ما زالت تعمل حتى اليوم؟", options: ["الأزهر بالقاهرة", "القرويين بفاس", "الزيتونة بتونس", "جامعة بولونيا"], correctIndex: 1 },
  { id: "q455", category: "تاريخ", difficulty: "easy", question: "من أي دولة انطلقت الثورة الصناعية أولاً؟", options: ["فرنسا", "ألمانيا", "بريطانيا", "أمريكا"], correctIndex: 2 },
  { id: "q456", category: "تاريخ", difficulty: "hard", question: "ما أول دولة اعترفت باستقلال الولايات المتحدة الأمريكية؟", options: ["فرنسا", "إسبانيا", "المغرب", "هولندا"], correctIndex: 2 },
  // ── رياضة ──
  { id: "q457", category: "رياضة", difficulty: "hard", question: "كم عدد لاعبي فريق الرغبي داخل الملعب؟", options: ["11", "13", "15", "9"], correctIndex: 2 },
  { id: "q458", category: "رياضة", difficulty: "medium", question: "كم عدد لاعبي الفريق في الكرة الطائرة الشاطئية؟", options: ["2", "4", "6", "1"], correctIndex: 0 },
  { id: "q459", category: "رياضة", difficulty: "medium", question: "مصطلح الضربة الساحقة شائع في رياضة: ماذا؟", options: ["كرة القدم", "التنس", "السباحة", "الرماية"], correctIndex: 1 },
  { id: "q460", category: "رياضة", difficulty: "medium", question: "ما هي المسافة الرسمية لسباق الماراثون؟", options: ["40 كم", "42.195 كم", "45 كم", "50 كم"], correctIndex: 1 },
  { id: "q461", category: "رياضة", difficulty: "easy", question: "ما المنتخب الأكثر تتويجاً بكأس العالم لكرة القدم؟", options: ["البرازيل", "ألمانيا", "إيطاليا", "الأرجنتين"], correctIndex: 0 },
  { id: "q462", category: "رياضة", difficulty: "medium", question: "كم عدد أشواط مباراة كرة السلة في الدوري الأمريكي؟", options: ["2", "3", "4", "6"], correctIndex: 2 },
  { id: "q463", category: "رياضة", difficulty: "medium", question: "من هو لاعب كرة القدم الملقب بالظاهرة؟", options: ["بيليه", "رونالدو البرازيلي", "زيدان", "كاكا"], correctIndex: 1 },
  { id: "q464", category: "رياضة", difficulty: "medium", question: "ما الدولة المضيفة للألعاب الأولمبية الصيفية 2028؟", options: ["فرنسا", "أمريكا", "أستراليا", "اليابان"], correctIndex: 1 },
  { id: "q465", category: "رياضة", difficulty: "medium", question: "في أي رياضة قتالية يُمنح الحزام الأسود كدرجة متقدمة؟", options: ["السباحة", "الجودو", "الرماية", "المصارعة الرومانية"], correctIndex: 1 },
  { id: "q466", category: "رياضة", difficulty: "medium", question: "كم عدد لاعبي فريق كرة اليد داخل الملعب؟", options: ["5", "6", "7", "9"], correctIndex: 2 },
  { id: "q467", category: "رياضة", difficulty: "medium", question: "الأسطورة بيليه مثّل منتخب أي دولة؟", options: ["الأرجنتين", "البرازيل", "البرتغال", "إسبانيا"], correctIndex: 1 },
  { id: "q468", category: "رياضة", difficulty: "easy", question: "من هو النادي الملقب بالنادي الملكي في إسبانيا؟", options: ["برشلونة", "ريال مدريد", "أتلتيكو مدريد", "إشبيلية"], correctIndex: 1 },
  { id: "q469", category: "رياضة", difficulty: "medium", question: "ما المنتخب الذي فاز بكأس آسيا لكرة القدم 2023؟", options: ["اليابان", "كوريا الجنوبية", "قطر", "السعودية"], correctIndex: 2 },
  { id: "q470", category: "رياضة", difficulty: "medium", question: "مصطلح هول إن ون خاص برياضة: ماذا؟", options: ["البولينغ", "الجولف", "الكروكيه", "البلياردو"], correctIndex: 1 },
  { id: "q471", category: "رياضة", difficulty: "medium", question: "كم عدد لاعبي فريق الكريكيت داخل الملعب؟", options: ["9", "10", "11", "13"], correctIndex: 2 },
  { id: "q472", category: "رياضة", difficulty: "easy", question: "رياضة البادل تشبه إلى حد كبير رياضة: ماذا؟", options: ["الاسكواش", "التنس", "كرة الطاولة", "الريشة الطائرة"], correctIndex: 1 },
  // ── فنون ──
  { id: "q473", category: "فنون", difficulty: "medium", question: "من رسم لوحة العشاء الأخير؟", options: ["مايكل أنجلو", "ليوناردو دافنشي", "رافاييل", "كارافاجيو"], correctIndex: 1 },
  { id: "q474", category: "فنون", difficulty: "medium", question: "من هو رائد المدرسة التكعيبية في الرسم؟", options: ["فان جوخ", "بيكاسو", "مونيه", "ماغريت"], correctIndex: 1 },
  { id: "q475", category: "فنون", difficulty: "medium", question: "من مؤلف السيمفونية التاسعة الشهيرة؟", options: ["موزارت", "بيتهوفن", "باخ", "شوبان"], correctIndex: 1 },
  { id: "q476", category: "فنون", difficulty: "medium", question: "من نحت منحوتة بييتا الموجودة في الفاتيكان؟", options: ["دوناتيلو", "مايكل أنجلو", "برنيني", "ليوناردو دافنشي"], correctIndex: 1 },
  { id: "q477", category: "فنون", difficulty: "hard", question: "من رسم لوحة انطباع شروق الشمس التي أخذت منها الحركة الانطباعية اسمها؟", options: ["رينوار", "كلود مونيه", "إدوارد مانيه", "سيزان"], correctIndex: 1 },
  { id: "q478", category: "فنون", difficulty: "medium", question: "في أي بلد نشأت موسيقى البلوز؟", options: ["بريطانيا", "فرنسا", "الولايات المتحدة", "البرازيل"], correctIndex: 2 },
  { id: "q479", category: "فنون", difficulty: "medium", question: "مسرح الغلوب المرتبط بمسرحيات شكسبير يقع في مدينة: ماذا؟", options: ["باريس", "روما", "لندن", "أثينا"], correctIndex: 2 },
  { id: "q480", category: "فنون", difficulty: "medium", question: "ما الخط العربي القديم الذي كُتبت به المصاحف الأولى؟", options: ["الخط الروماني", "الخط الكوفي", "الخط اللاتيني", "الخط الإغريقي"], correctIndex: 1 },
  { id: "q481", category: "فنون", difficulty: "medium", question: "من هو مؤلف رواية البؤساء؟", options: ["ألكسندر دوما", "فيكتور هوغو", "بلزاك", "إميل زولا"], correctIndex: 1 },
  { id: "q482", category: "فنون", difficulty: "hard", question: "أهدت فرنسا تمثال الحرية لأمريكا بمناسبة: ماذا؟", options: ["نهاية الحرب العالمية الأولى", "مئوية استقلال أمريكا", "معاهدة فرساي", "اكتشاف أمريكا"], correctIndex: 1 },
  { id: "q483", category: "فنون", difficulty: "hard", question: "لوحة غيرنيكا لبيكاسو كانت احتجاجاً على: ماذا؟", options: ["الحرب العالمية الأولى", "الحرب الأهلية الإسبانية", "الحرب الباردة", "حرب فيتنام"], correctIndex: 1 },
  { id: "q484", category: "فنون", difficulty: "easy", question: "فن الأوريغامي الياباني يقوم على طي: ماذا؟", options: ["القماش", "الورق", "المعدن", "الخشب"], correctIndex: 1 },
  // ── تكنولوجيا ──
  { id: "q485", category: "تكنولوجيا", difficulty: "medium", question: "في أي عام تأسست شركة أبل؟", options: ["1971", "1976", "1980", "1984"], correctIndex: 1 },
  { id: "q486", category: "تكنولوجيا", difficulty: "medium", question: "من هو مخترع شبكة الويب العالمية؟", options: ["بيل غيتس", "تيم بيرنرز لي", "فينت سيرف", "ستيف وزنياك"], correctIndex: 1 },
  { id: "q487", category: "تكنولوجيا", difficulty: "hard", question: "ما الشركة التي طوّرت نظام أندرويد قبل أن تستحوذ عليه جوجل؟", options: ["نوكيا", "شركة أندرويد", "مايكروسوفت", "سامسونج"], correctIndex: 1 },
  { id: "q488", category: "تكنولوجيا", difficulty: "medium", question: "ما لغة البرمجة التي طورتها شركة صن ميكروسيستمز ورمزها فنجان قهوة؟", options: ["جافا", "باسكال", "روبي", "بيرل"], correctIndex: 0 },
  { id: "q489", category: "تكنولوجيا", difficulty: "medium", question: "ماذا يعني اختصار RAM في الحاسوب؟", options: ["ذاكرة القراءة فقط", "ذاكرة الوصول العشوائي", "ذاكرة التخزين الدائم", "ذاكرة التخزين المؤقت"], correctIndex: 1 },
  { id: "q490", category: "تكنولوجيا", difficulty: "easy", question: "البايت الواحد في الحاسوب يساوي: كم بت؟", options: ["4", "6", "8", "16"], correctIndex: 2 },
  { id: "q491", category: "تكنولوجيا", difficulty: "easy", question: "ما الشركة التي تطوّر نظام تشغيل أندرويد؟", options: ["أبل", "جوجل", "مايكروسوفت", "سامسونج"], correctIndex: 1 },
  { id: "q492", category: "تكنولوجيا", difficulty: "easy", question: "ما الشركة المالكة لمنصة يوتيوب؟", options: ["أبل", "جوجل", "أمازون", "فيسبوك"], correctIndex: 1 },
  { id: "q493", category: "تكنولوجيا", difficulty: "easy", question: "من هو مخترع الهاتف؟", options: ["توماس إديسون", "ألكسندر غراهام بيل", "نيكولا تسلا", "غولييلمو ماركوني"], correctIndex: 1 },
  { id: "q494", category: "تكنولوجيا", difficulty: "easy", question: "ما اسم المساعد الصوتي في أجهزة أبل؟", options: ["أليكسا", "سيري", "كورتانا", "جيميني"], correctIndex: 1 },
  { id: "q495", category: "تكنولوجيا", difficulty: "medium", question: "في أي عام أُطلق موقع فيسبوك؟", options: ["1998", "2004", "2006", "2008"], correctIndex: 1 },
  { id: "q496", category: "تكنولوجيا", difficulty: "medium", question: "ماذا يعني اختصار GPS؟", options: ["نظام الملاحة الجوية", "النظام العالمي لتحديد المواقع", "نظام الخرائط الرقمية", "البروتوكول العام للتوجيه"], correctIndex: 1 },
  { id: "q497", category: "تكنولوجيا", difficulty: "medium", question: "بأي وحدة تقاس سرعة الإنترنت عادة؟", options: ["ميغابايت في الدقيقة", "ميغابت في الثانية", "غيغاهرتز", "تيرابايت"], correctIndex: 1 },
  { id: "q498", category: "تكنولوجيا", difficulty: "easy", question: "من هما مؤسسا محرك بحث جوجل؟", options: ["ستيف جوبز وستيف وزنياك", "بيل غيتس وبول ألين", "لاري بيج وسيرغي برين", "جيف بيزوس وأندي جاسي"], correctIndex: 2 },
  { id: "q499", category: "تكنولوجيا", difficulty: "medium", question: "ماذا يعني اختصار HTTP؟", options: ["لغة ترميز النصوص", "بروتوكول نقل النص التشعبي", "عنوان موقع إلكتروني", "نظام تشفير البيانات"], correctIndex: 1 },
  { id: "q500", category: "تكنولوجيا", difficulty: "easy", question: "ما المتصفح الذي طورته مايكروسوفت ويأتي مدمجاً مع ويندوز؟", options: ["كروم", "سفاري", "إيدج", "فايرفوكس"], correctIndex: 2 },
  { id: "q501", category: "تكنولوجيا", difficulty: "medium", question: "ما اسم خدمة الحوسبة السحابية التابعة لشركة أمازون؟", options: ["Azure", "AWS", "Google Cloud", "IBM Cloud"], correctIndex: 1 },
  { id: "q502", category: "تكنولوجيا", difficulty: "hard", question: "من هو المؤسس الشاب لعملة إيثيريوم الرقمية؟", options: ["سام بانكمان فريد", "فيتاليك بوتيرين", "تشانغبينغ تشاو", "ساتوشي ناكاموتو"], correctIndex: 1 },
  // ── أفلام ومسلسلات ──
  { id: "q503", category: "أفلام ومسلسلات", difficulty: "easy", question: "ما الشركة التي أنتجت فيلم الأسد الملك؟", options: ["ديزني", "وارنر بروس", "يونيفرسال", "باراماونت"], correctIndex: 0 },
  { id: "q504", category: "أفلام ومسلسلات", difficulty: "medium", question: "بأي شخصية اشتهر الممثل هيو جاكمان؟", options: ["سبايدرمان", "وولفرين", "باتمان", "سوبرمان"], correctIndex: 1 },
  { id: "q505", category: "أفلام ومسلسلات", difficulty: "medium", question: "مسلسل صراع العروش مأخوذ عن روايات من تأليف: مَن؟", options: ["ج.ك. رولينغ", "جورج آر آر مارتن", "تولكين", "ستيفن كينغ"], correctIndex: 1 },
  { id: "q506", category: "أفلام ومسلسلات", difficulty: "medium", question: "من بطلة فيلم باربي عام 2023؟", options: ["إيما ستون", "مارغو روبي", "آن هاثاواي", "سكارليت جوهانسون"], correctIndex: 1 },
  { id: "q507", category: "أفلام ومسلسلات", difficulty: "medium", question: "من هو مخرج فيلم العرّاب؟", options: ["مارتن سكورسيزي", "فرانسيس فورد كوبولا", "سبايك لي", "براين دي بالما"], correctIndex: 1 },
  { id: "q508", category: "أفلام ومسلسلات", difficulty: "easy", question: "من هو النجم الرئيسي في سلسلة أفلام الماتريكس؟", options: ["براد بيت", "كيانو ريفز", "توم هانكس", "ويل سميث"], correctIndex: 1 },
  { id: "q509", category: "أفلام ومسلسلات", difficulty: "easy", question: "من يؤدي شخصية الكابتن جاك سبارو في قراصنة الكاريبي؟", options: ["براد بيت", "جوني ديب", "أورلاندو بلوم", "توم كروز"], correctIndex: 1 },
  { id: "q510", category: "أفلام ومسلسلات", difficulty: "medium", question: "فيلم الأنمي الشهير المخطوفة من إخراج: مَن؟", options: ["ساتوشي كون", "هاياو ميازاكي", "ماكوتو شينكاي", "إيساو تاكاهاتا"], correctIndex: 1 },
  { id: "q511", category: "أفلام ومسلسلات", difficulty: "medium", question: "في أي مدينة تدور أحداث مسلسل فريندز؟", options: ["لوس أنجلوس", "نيويورك", "شيكاغو", "بوسطن"], correctIndex: 1 },
  { id: "q512", category: "أفلام ومسلسلات", difficulty: "medium", question: "من بطل فيلم جوكر عام 2019؟", options: ["هيث ليدجر", "خواكين فينيكس", "جاريد ليتو", "روبرت باتينسون"], correctIndex: 1 },
  { id: "q513", category: "أفلام ومسلسلات", difficulty: "easy", question: "من هو نجم سلسلة أفلام السرعة والغضب؟", options: ["دواين جونسون", "فين ديزل", "جيسون ستاثام", "توم كروز"], correctIndex: 1 },
  { id: "q514", category: "أفلام ومسلسلات", difficulty: "medium", question: "من هي بطلة فيلم تايتانيك الشهير؟", options: ["كيت بلانشيت", "كيت وينسلت", "جوليا روبرتس", "نيكول كيدمان"], correctIndex: 1 },
  { id: "q515", category: "أفلام ومسلسلات", difficulty: "medium", question: "من بطل فيلم غاتسبي العظيم بنسخة 2013؟", options: ["توبي ماغواير", "ليوناردو دي كابريو", "روبرت ريدفورد", "هيو جاكمان"], correctIndex: 1 },
  { id: "q516", category: "أفلام ومسلسلات", difficulty: "easy", question: "في كرتون توم وجيري، ما اسم القط؟", options: ["جيري", "توم", "سبايك", "بوتش"], correctIndex: 1 },
  // ── طعام ومشروبات ──
  { id: "q517", category: "طعام ومشروبات", difficulty: "easy", question: "ما المكوّن الأساسي لطبق الفول المدمس؟", options: ["العدس", "الحمص", "الفول", "الفاصولياء"], correctIndex: 2 },
  { id: "q518", category: "طعام ومشروبات", difficulty: "medium", question: "ما المشروب الياباني التقليدي المصنوع من الأرز المخمر؟", options: ["الماتشا", "الساكي", "الصويا", "الزنجبيل"], correctIndex: 1 },
  { id: "q519", category: "طعام ومشروبات", difficulty: "easy", question: "طبق التاكو نشأ أصلاً في: ماذا؟", options: ["إسبانيا", "المكسيك", "بيرو", "الولايات المتحدة"], correctIndex: 1 },
  { id: "q520", category: "طعام ومشروبات", difficulty: "medium", question: "ما هو الموطن الأصلي لشجرة الكاكاو؟", options: ["أفريقيا", "آسيا", "أمريكا الجنوبية والوسطى", "أوروبا"], correctIndex: 2 },
  { id: "q521", category: "طعام ومشروبات", difficulty: "medium", question: "الخبز الهندي المسطح المسمى نان يُخبز عادة في: ماذا؟", options: ["مقلاة مسطحة", "فرن طيني", "شواية", "ميكروويف"], correctIndex: 1 },
  { id: "q522", category: "طعام ومشروبات", difficulty: "easy", question: "من ماذا يُصنع اللبن الرائب؟", options: ["الكريمة", "الحليب", "الماء", "عصير الليمون"], correctIndex: 1 },
  { id: "q523", category: "طعام ومشروبات", difficulty: "medium", question: "ثمرة الأفوكادو تصنف نباتياً ضمن: ماذا؟", options: ["الخضروات", "الفواكه", "الحبوب", "الجذور"], correctIndex: 1 },
  { id: "q524", category: "طعام ومشروبات", difficulty: "easy", question: "طبق السوشي ينتمي إلى مطبخ: أي دولة؟", options: ["الصين", "كوريا", "اليابان", "تايلاند"], correctIndex: 2 },
  { id: "q525", category: "طعام ومشروبات", difficulty: "medium", question: "ما البهار الأصفر الأساسي في أطباق الكاري؟", options: ["الزعفران", "الكركم", "الكمون", "الكزبرة"], correctIndex: 1 },
  { id: "q526", category: "طعام ومشروبات", difficulty: "hard", question: "حلوى الماكارون الفرنسية تُصنع أساساً من: ماذا؟", options: ["دقيق القمح", "دقيق اللوز", "دقيق الأرز", "نشا الذرة"], correctIndex: 1 },
  { id: "q527", category: "طعام ومشروبات", difficulty: "medium", question: "حلوى التيراميسو الإيطالية تحتوي على: ماذا؟", options: ["الجيلاتو", "جبن الماسكاربوني والقهوة", "البانيتون", "الريزوتو"], correctIndex: 1 },
  { id: "q528", category: "طعام ومشروبات", difficulty: "hard", question: "جبن الغورغونزولا ذو العفن الأزرق أصله من: أي دولة؟", options: ["فرنسا", "إيطاليا", "سويسرا", "هولندا"], correctIndex: 1 },
  // ── حيوانات ──
  { id: "q529", category: "حيوانات", difficulty: "easy", question: "ما هي أكبر سمكة في العالم؟", options: ["القرش الأبيض", "قرش الحوت", "الحوت الأزرق", "التونة"], correctIndex: 1 },
  { id: "q530", category: "حيوانات", difficulty: "medium", question: "ما هو الطائر الوحيد القادر على الطيران إلى الخلف؟", options: ["العصفور", "الطنان", "الببغاء", "الخطاف"], correctIndex: 1 },
  { id: "q531", category: "حيوانات", difficulty: "hard", question: "ما هو الثديي الوحيد الذي يبيض؟", options: ["البطريق", "خلد الماء", "القنفذ", "الكنغر"], correctIndex: 1 },
  { id: "q532", category: "حيوانات", difficulty: "easy", question: "ما الحيوان الأسترالي الذي يحمل صغيره في جيب؟", options: ["الكوالا", "الكنغر", "الدب", "الغزال"], correctIndex: 1 },
  { id: "q533", category: "حيوانات", difficulty: "easy", question: "ماذا يسمى صوت الأسد؟", options: ["نهيق", "زئير", "نباح", "مواء"], correctIndex: 1 },
  { id: "q534", category: "حيوانات", difficulty: "easy", question: "على ماذا يتغذى حيوان الباندا بشكل أساسي؟", options: ["اللحوم", "الخيزران", "الأسماك", "الفواكه"], correctIndex: 1 },
  { id: "q535", category: "حيوانات", difficulty: "medium", question: "كم عدد أرجل السلطعون البحري؟", options: ["6", "8", "10", "12"], correctIndex: 2 },
  { id: "q536", category: "حيوانات", difficulty: "easy", question: "أين يعيش الدب القطبي؟", options: ["القطب الجنوبي", "القطب الشمالي", "جبال الألب", "صحراء كلهاري"], correctIndex: 1 },
  { id: "q537", category: "حيوانات", difficulty: "medium", question: "ما الموطن الأصلي لحيوان اللاما؟", options: ["آسيا الوسطى", "أفريقيا", "أمريكا الجنوبية", "أستراليا"], correctIndex: 2 },
  { id: "q538", category: "حيوانات", difficulty: "easy", question: "أين تعيش البرمائيات؟", options: ["في الماء وعلى اليابسة", "في الماء فقط", "على اليابسة فقط", "في الجو"], correctIndex: 0 },
  { id: "q539", category: "حيوانات", difficulty: "easy", question: "بماذا يغطى جسم حيوان النيص؟", options: ["الصوف", "الأشواك", "الحراشف", "الريش"], correctIndex: 1 },
  { id: "q540", category: "حيوانات", difficulty: "medium", question: "مما يتكون غذاء الغوريلا غالباً؟", options: ["اللحوم", "النباتات", "الحشرات", "الأسماك"], correctIndex: 1 },
  { id: "q541", category: "حيوانات", difficulty: "medium", question: "مما تخرج الفراشة بعد اكتمال نموها؟", options: ["البيضة", "الشرنقة", "العش", "اليرقة"], correctIndex: 1 },
  { id: "q542", category: "حيوانات", difficulty: "medium", question: "أي نوع من الأشعة يستطيع النحل رؤيته؟", options: ["تحت الحمراء", "فوق البنفسجية", "السينية", "الجاما"], correctIndex: 1 },
];
