/**
 * The shared question bank used by every challenge.
 * Each round picks a random subset, so friends never play the same questions twice.
 */

export type Question = {
  id: string;
  category: string;
  question: string;
  options: [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
};

export const QUESTION_BANK: Question[] = [
  {
    id: "q01",
    category: "عام",
    question: "ما هو أكبر محيط على وجه الأرض؟",
    options: ["المحيط الهادئ", "المحيط الأطلسي", "المحيط الهندي", "المحيط المتجمد الشمالي"],
    correctIndex: 0,
  },
  {
    id: "q02",
    category: "عام",
    question: "كم عدد ألوان قوس قزح؟",
    options: ["ستة", "سبعة", "خمسة", "ثمانية"],
    correctIndex: 1,
  },
  {
    id: "q03",
    category: "عام",
    question: "ما هو الحيوان الملقَّب بـ«سفينة الصحراء»؟",
    options: ["الحصان", "الفيل", "الجمل", "الحمار"],
    correctIndex: 2,
  },
  {
    id: "q04",
    category: "عام",
    question: "ما هي العملة الرسمية في اليابان؟",
    options: ["اليوان", "الين", "الوون", "الدرهم"],
    correctIndex: 1,
  },
  {
    id: "q05",
    category: "عام",
    question: "ما هو اللون الناتج عن خلط الأزرق مع الأصفر؟",
    options: ["الأخضر", "البنفسجي", "البرتقالي", "البني"],
    correctIndex: 0,
  },
  {
    id: "q06",
    category: "عام",
    question: "كم عدد أيام السنة الكبيسة؟",
    options: ["365", "366", "364", "360"],
    correctIndex: 1,
  },
  {
    id: "q07",
    category: "عام",
    question: "ما هو أكبر عضو في جسم الإنسان؟",
    options: ["الجلد", "الكبد", "الدماغ", "الرئتان"],
    correctIndex: 0,
  },
  {
    id: "q08",
    category: "علوم",
    question: "ما هو الكوكب الأقرب إلى الشمس؟",
    options: ["الزهرة", "المريخ", "الأرض", "عطارد"],
    correctIndex: 3,
  },
  {
    id: "q09",
    category: "علوم",
    question: "ما هو الغاز الذي تمتصّه النباتات من الجو أثناء التمثيل الضوئي؟",
    options: ["الأكسجين", "ثاني أكسيد الكربون", "النيتروجين", "الهيدروجين"],
    correctIndex: 1,
  },
  {
    id: "q10",
    category: "علوم",
    question: "كم عدد عظام جسم الإنسان البالغ تقريباً؟",
    options: ["306", "266", "206", "106"],
    correctIndex: 2,
  },
  {
    id: "q11",
    category: "علوم",
    question: "ما هو العنصر الكيميائي الذي رمزه O؟",
    options: ["الذهب", "الهيدروجين", "الأوزون", "الأكسجين"],
    correctIndex: 3,
  },
  {
    id: "q12",
    category: "علوم",
    question: "ما هو أسرع حيوان بري في العالم؟",
    options: ["النمر", "الغزال", "الفهد", "الحصان"],
    correctIndex: 2,
  },
  {
    id: "q13",
    category: "جغرافيا",
    question: "ما هي عاصمة اليابان؟",
    options: ["أوساكا", "طوكيو", "كيوتو", "هيروشيما"],
    correctIndex: 1,
  },
  {
    id: "q14",
    category: "جغرافيا",
    question: "ما هي أكبر دولة عربية من حيث المساحة؟",
    options: ["السعودية", "السودان", "مصر", "الجزائر"],
    correctIndex: 3,
  },
  {
    id: "q15",
    category: "جغرافيا",
    question: "ما هو أطول نهر في أفريقيا؟",
    options: ["الكونغو", "النيجر", "النيل", "زامبيزي"],
    correctIndex: 2,
  },
  {
    id: "q16",
    category: "جغرافيا",
    question: "ما هي أصغر قارة في العالم؟",
    options: ["أوروبا", "القارة القطبية الجنوبية", "أستراليا", "أمريكا الجنوبية"],
    correctIndex: 2,
  },
  {
    id: "q17",
    category: "جغرافيا",
    question: "أي دولة عربية تُلقَّب بـ«بلد المليون شهيد»؟",
    options: ["تونس", "المغرب", "ليبيا", "الجزائر"],
    correctIndex: 3,
  },
  {
    id: "q18",
    category: "رياضيات",
    question: "كم يساوي 7 × 8؟",
    options: ["54", "64", "56", "48"],
    correctIndex: 2,
  },
  {
    id: "q19",
    category: "رياضيات",
    question: "ما هو ناتج 9 + 9 ÷ 3؟",
    options: ["18", "6", "12", "15"],
    correctIndex: 2,
  },
  {
    id: "q20",
    category: "رياضيات",
    question: "ما هو العدد الذي إذا ضربته في نفسه كان الناتج 144؟",
    options: ["12", "14", "11", "16"],
    correctIndex: 0,
  },
  {
    id: "q21",
    category: "رياضيات",
    question: "ما هو نصف رُبع العدد 400؟",
    options: ["100", "200", "25", "50"],
    correctIndex: 3,
  },
  {
    id: "q22",
    category: "رياضيات",
    question: "إذا كانت الساعة 60 دقيقة، فكم دقيقة في ساعة ونصف؟",
    options: ["90", "75", "100", "80"],
    correctIndex: 0,
  },
  {
    id: "q23",
    category: "لغة",
    question: "ما هو جمع كلمة «كتاب»؟",
    options: ["كتائب", "كتب", "أكتب", "كتابات"],
    correctIndex: 1,
  },
  {
    id: "q24",
    category: "لغة",
    question: "ما هو مفرد كلمة «أقلام»؟",
    options: ["قلام", "قلم", "قلّم", "أقلم"],
    correctIndex: 1,
  },
  {
    id: "q25",
    category: "لغة",
    question: "كم عدد حروف اللغة العربية؟",
    options: ["26", "30", "28", "29"],
    correctIndex: 2,
  },
  {
    id: "q26",
    category: "لغة",
    question: "ما هو عكس كلمة «الهدوء»؟",
    options: ["السكينة", "الطمأنينة", "الضجيج", "الراحة"],
    correctIndex: 2,
  },
  {
    id: "q27",
    category: "منطق",
    question: "ما هو العدد التالي في المتتالية: 2، 4، 8، 16، …؟",
    options: ["24", "30", "32", "64"],
    correctIndex: 2,
  },
  {
    id: "q28",
    category: "منطق",
    question: "لديك 3 تفاحات وأخذت اثنتين، كم تفاحة أصبحت معك؟",
    options: ["3", "1", "2", "5"],
    correctIndex: 2,
  },
  {
    id: "q29",
    category: "منطق",
    question: "إذا كان اليوم هو الثلاثاء، فما هو اليوم بعد غدٍ؟",
    options: ["الأربعاء", "الخميس", "الجمعة", "الاثنين"],
    correctIndex: 1,
  },
  {
    id: "q30",
    category: "منطق",
    question: "ما هو الرقم الذي يلي 99 مباشرةً عند العدّ التنازلي؟",
    options: ["98", "97", "100", "89"],
    correctIndex: 0,
  },
  {
    id: "q31",
    category: "تاريخ",
    question: "في أي عام انتهت الحرب العالمية الثانية؟",
    options: ["1939", "1945", "1943", "1918"],
    correctIndex: 1,
  },
  {
    id: "q32",
    category: "تاريخ",
    question: "من هو أول إنسان سافر إلى الفضاء؟",
    options: ["نيل أرمسترونغ", "باز ألدرين", "فالنتينا تيريشكوفا", "يوري غاغارين"],
    correctIndex: 3,
  },
  {
    id: "q33",
    category: "تاريخ",
    question: "في أي مدينة أقيمت دورة الألعاب الأولمبية عام 2024؟",
    options: ["طوكيو", "لندن", "باريس", "لوس أنجلوس"],
    correctIndex: 2,
  },
  {
    id: "q34",
    category: "رياضة",
    question: "كم عدد لاعبي فريق كرة القدم داخل الملعب؟",
    options: ["10", "12", "9", "11"],
    correctIndex: 3,
  },
  {
    id: "q35",
    category: "رياضة",
    question: "ما هي الرياضة التي يمارسها «نوفاك ديوكوفيتش»؟",
    options: ["السباحة", "التنس", "الغولف", "كرة السلة"],
    correctIndex: 1,
  },
  {
    id: "q36",
    category: "فنون",
    question: "من هو الرسام الشهير الذي رسم «الموناليزا»؟",
    options: ["فان جوخ", "بيكاسو", "ليوناردو دافنشي", "ريمبرانت"],
    correctIndex: 2,
  },
  {
    id: "q37",
    category: "فنون",
    question: "كم عدد أوتار آلة الكمان؟",
    options: ["6", "4", "5", "7"],
    correctIndex: 1,
  },
];
